### ISSUE TITLE
Query Generation doesn't give property information

### ISSUE THREAD

**Issue by BlakeMScurr** [codelingo/ideplugins#3]
If you generate a query (with StructName highlighted) on 
```
type StructName struct {
	FieldName *string `json:"name"`
}
```

You get:
```
go.package:
  go.file:
    go.gen_decl:
      go.type_spec:
        go.ident:
```

Which provides no information on what to query underneath "go.ident".
